<a href="https://colab.research.google.com/github/filippocasari/ML_AS2_filippo_casari/blob/main/ML_AS2_filippo_casari.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Machine Learning 2021/2022
## Assignment 2: Probabilistic Modeling, Unsupervised Learning, Reinforcement Learning
Deadline: 20th of December 2021 9pm

First name: Filippo  
Last name: Casari

## About this assignment

In this assignment you will further deepen your understanding of Probabilistic Modeling, Unsupervised Learning, and Reinforcement Learning (RL).

## Submission instructions

Please write your answers, equations, and code directly in this python notebook and print the final result to pdf (File > Print).
Make sure that code has appropriate line breaks such that all code is visible in the final pdf.
If necessary, select A3 for the PDF size to prevent content from being clipped.

The final pdf must be named name.lastname.pdf and uploaded to the iCorsi website before the deadline expires. Late submissions will result in 0 points.

**Also share this notebook (top right corner 'Share') with teaching.idsia@gmail.com during submission.**

**Keep your answers brief and respect the sentence limits in each question (answers exceeding the limit are not taken into account)**.

Note that there are a total of **140 points in this assignment**.

Learn more about python notebooks and formatting here: https://colab.research.google.com/notebooks/welcome.ipynb

## How to get help

We encourage you to use the tutorials to ask questions or to discuss exercises with other students.
However, do not look at any report written by others or share your report with others.
Violation of that rule will result in 0 points for all students involved. For further questions you can contact the respective TA:

- Probabilistic Modeling: louis@idsia.ch
- Unsupervised Learning: anand@idsia.ch
- Reinforcement Learning: dylan.ashley@idsia.ch

## 1 Probabilistic Modeling (20p)

If $X \sim \text{Rayleigh}(\lambda)$ is a Rayleigh random variable then its probability density function is given by 
\begin{equation*}
    p(x; \lambda) = \frac{2x}{\lambda} e^{-\frac{x^2}{\lambda}} \ \ \text{for} \ \ x \geq 0.
\end{equation*}
Let $(X_1, X_2, \ldots, X_N)$ be a random sample from the Rayleigh distribution with parameter $\lambda$ and let $\mathcal{D} = (x_1, x_2, \ldots, x_N)$ be its realization.

### Question 1.1 (4p)

Derive the likelihood function of $\lambda$ given $\mathcal{D}$.  Include all intermediate steps. Simplify sums and products.

$$\mathcal{L}(\lambda; \mathcal{D}) = ?$$

---
$$\mathcal
 L(\lambda, D)=\prod _{i=1}^{n}(\frac{2x_{i}}{\lambda})e^{\frac{-x_{i}^{2}}{\lambda}}=(\frac{2}{\lambda})^{n}e^{-\sum_{i=1}^{n}{x_{i}^{2}/\lambda}}\prod_{i=1}^{n} {x_{i}}
 $$

### Question 1.2 (2p)

Derive the log-likelihood. Include all intermediate steps.

$$\ln \mathcal{L}(\lambda; \mathcal{D}) = ?$$

---
$$\mathcal
 \ln{L(\lambda, D)}=\ln{(\prod _{i=1}^{n}(\frac{2x_{i}}{\lambda})e^{\frac{-x_{i}^{2}}{\lambda}}=(\frac{2}{\lambda})^{n}e^{-\sum_{i=1}^{n}{x_{i}^{2}/\lambda}}\prod_{i=1}^{n} {x_{i}})}\\=\ln{\frac{2}{\lambda}^{n}}+ln{e^{\frac{-x_{i}^{2}}{\lambda}}}+ln{\prod _{i=1}^{n}{x_{i}}}=n\ln{2}-n\ln{\lambda}-\lambda\sum_{i=1}^{n}{x_{i}^{2}}+\sum_{i=1}^{n}{\ln{x_{i}}}
 $$

### Question 1.3 (6p)

Derive the maximum likelihood estimate for $\lambda$. Include all intermediate steps.

---

$$\frac{\partial }{\partial \lambda} \ln{L(\lambda, D)}=0\; we \;have\; to\; set\; this\;to\; zero\;$$

$$\frac{\partial }{\partial \lambda}{nln2}-\frac{\partial }{\partial \lambda}{nln{\lambda}}-\sum_{i=1}^{n}\frac{\partial }{\partial \lambda}(\frac{1}{\lambda})+\frac{\partial }{\partial \lambda}(\sum_{i}^{n}{\ln{x_{i}^{2}}})=0$$

$$-\frac{n}{\lambda}+\sum{x_{i}^{2}}(\frac{1}{\lambda^{2}})=0$$

$$-n+\sum{x_{i}^{2}}(\frac{1}{\lambda})=0$$

$$\lambda=\frac{1}{n}\sum{x_{i}^{2}}$$


we must compute the second derivative to be sure that
we found the local maximum and not the local minimum of our function
$$\frac{\partial^2 }{\partial \lambda^2}\ln{L(\lambda, D)}=\frac{\partial }{\partial \lambda}[-\frac{n}{\lambda}+\sum{x_{i}^{2}}(\frac{1}{\lambda^{2}})]$$
$$=\frac{n}{\lambda^{2}}-2\sum_{i=1}^{n}{\frac{x_{i}^{2}}{\lambda^{3}}}$$
$$=\frac{[n\lambda-2\sum_{i=1}^{n}x_{i}^{2}]}{\lambda^{3}}$$
$$=\frac{-n^{3}}{(\sum{x_{i}^{2}})^{2}}<0\;
with
\sum{x_{i}^{2}} \neq 0$$
we can underline that the last term is less than zero, so we have found the maximum.


### Question 1.4 (8p)

Now, suppose we have an inverse gamma prior with parameters $\alpha$ and $\beta$ on $\lambda$, i.e. the probability density function of the prior is
\begin{equation*}
    p(\lambda; \alpha, \beta) = \frac{\beta^\alpha}{\Gamma(\alpha)} \lambda^{-(\alpha + 1)} e^{-\beta / \lambda}
\end{equation*}
where $\Gamma(\cdot)$ is the gamma function defined as $\Gamma(t) = \int_0^\infty u^{t-1} e^{-u} \mathrm{d}u$.

What is the maximum a posteriori estimate for $\lambda$? Include all intermediate steps.

---



from Bayes Theorem: $$P(\lambda\mid D)=\frac{P(\lambda\mid D)P(\lambda)}{P(D)}$$\\}

$$\lambda=argmax(P(\lambda\mid D)=(\frac{P(\lambda\mid D)P(\lambda)}{P(D)})\\$$
$$ln(\frac{P(\lambda\mid D)P(\lambda)}{P(D)})=ln(P(\lambda\mid D))-ln(P(D))+P(\lambda)=*\\$$

Now we have to take the first derivative
$$\frac{\partial }{\partial \lambda}[*]$$
 but the term $$ln(P(D))$$
does not depend on lambda, so the derivative respect to lambda is =0
we know from 1.2 what is $$ln(P(\lambda\mid D))$$

$$\frac{\partial }{\partial \lambda}(nln(\lambda)-ln(\lambda)-\sum_{i=1}^{n}(\frac{x_{i}^{2}}{\lambda})+ \sum(ln(x_{i})))+\frac{\partial }{\partial \lambda}ln(\frac{\beta^\alpha}{\Gamma(\alpha)} \lambda^{-(\alpha + 1)} e^{-\beta / \lambda})$$
$$=\frac{-n}{\lambda}+\frac{\sum(x_{i}^{2})}{\lambda^{2}}-\frac{(\alpha+1)}{\lambda}+\frac{\beta}{\lambda^{2}}=0$$
$$- n +\frac{1}{\lambda} \sum (x_{i}^{2})-(\alpha+1) +\frac{\beta}{\lambda}=0$$
$$-\lambda n+\sum(x_{i}^{2})-\lambda (\alpha+1) +\beta=0$$
$$\lambda (n+ \alpha +1)= \sum(x_{i}^2)$$
$$\lambda=\frac{\sum(x_{i}^{2}) + \beta}{n+1+\alpha}$$

## 2 Unsupervised Learning (30p)

### Question 2.1 (5p)
Given a dataset of points in 1-dimension i.e. $X = \{0, 2, 4, 8, 12 \}$, initialize the k-Means algorithm with 2 cluster center(s) as $\mu_1$ = 0 and $\mu_2$ = 12. Perform 1 iteration (1 E-step and 1 M-step) of the k-Means algorithm with the given cluster initializations.  Compute cluster assignments for all datapoints and cluster centers at the end of the iteration. (Show **all** intermediate computation steps).
 
---
$$\ 
\text{We can consider the Euclidean distance defined as }\\
Distance=D=\left | p-q_{i} \right |\\ \text{ where p and q are points; in this case p is the center of one cluster and q(i) is a generic point}
$$

\\
\begin{array}{|c | c |c | c|}\hline
     \text{ Datapoints } & \text{ D1 } & \text{ D2 } &\text{Cluster}\\\hline
     0       & 0           & 12  & C1\\\hline
     2     & 2              & 10 & C1\\\hline
     4    & 4             & 8    & C1  \\\hline
     8       & 8        &  4   & C2    \\\hline
     12     & 12              &  0 &   C2\\\hline
\end{array} 


D1 is the distance from the center of the first cluster, D2 from the center of the second cluster. We have to compare these two distances and assign that point to the cluster which has the shortest distance as showed above.



### Question 2.2 (10p)
For the k-Means algorithm, given a dataset $X = \{ x_1, x_2, ... , x_i, ... , x_n \}$ of $n$ points where $x_i \in \mathbb{R}^d$. We want to cluster this into $k$ clusters with centers $\mu = (\mu_1, ..., \mu_k)$. Show that k-Means is guaranteed to converge to a local optimum. Convergence criteria is said to have been met in k-Means when no change of cluster assignment happens for any datapoint between iteration $t$ and $t+1$. *Hint:* Prove that the loss function decreases monotonically in each iteration until convergence (prove it separately for both the E-step and M-step).


---

**ANSWER HERE**

### Question 2.3 (5p)
Find the Eigendecomposition (i.e. eigenvalues and eigenvectors) for 
\begin{equation}
 A = \begin{bmatrix} 
 3 & 5 \\ 4 & 2 
 \end{bmatrix}
\end{equation}

---
\begin{equation}
(A-\lambda I)=0\\
\begin{pmatrix}
3&5 \\ 4& 2\end{pmatrix}
-\begin{pmatrix}\lambda & 0\\
0& \lambda\end{pmatrix}=0\\
\begin{pmatrix}
3-\lambda & 5\\ 
 4&2- \lambda
\end{pmatrix}=0\\
(2-\lambda)^2-20=0\\
\lambda^{2}-5 \lambda-14=0\\
\lambda_{1}=7\, and\; \lambda_{2}=-2\\
 \text{now let's compute the first eigenvector}\\ \end{equation}
 \begin{equation}
(A-\lambda_{1} I)v_{1}=0\\
\begin{pmatrix}
3-7 &5 \\
 4&2-7 
\end{pmatrix}\begin{pmatrix}
v_{1,1}\\v_{1,2}
\end{pmatrix}=\begin{pmatrix}
0\\ 0
\end{pmatrix} \\
v_{1,2}=\frac{4}{5}v_{1,1}\\\\
v_{1}=k_{1}\begin{pmatrix}
1\\ \frac{4}{5}
\end{pmatrix} \text{where k1 is an arbitrary constant}\end{equation}
I applied the sam mechanism for the second eingenvalue and eigenvector. 
\begin{equation}
(A-\lambda_{2} I)v_{2}=0\\ \\
\begin{pmatrix}
3+2 &5 \\ \\
 4&2+2 
\end{pmatrix}\begin{pmatrix}
v_{2,1}\\v_{2,2}
\end{pmatrix}=\begin{pmatrix}
0\\ 0
\end{pmatrix} \\\\\\
v_{2,2}=-v_{2,1}\\\\
v_{2}=k_{2}\begin{pmatrix}
1\\ -1
\end{pmatrix}
\end{equation}


### Question 2.4 (10p)
Prove that a linear projection onto an $M$-dimensional subspace that maximizes the variance of the projected data is defined by the $M$ eigenvectors of the data covariance matrix $S$, corresponding to the $M$ largest eigenvalues. *Hint:* We showed this for the simple 1-D case in the TA session. Now extend this proof for the general case $M < D$ using induction.

---

**ANSWER HERE**

## 3 Reinforcement Learning: Markov Decision Processes (32p)

Suppose a robot is put in a maze with a long corridor. The
corridor is 1 kilometer long and 5 meters wide. The available actions to the robot are moving forward 1 meter, moving backward 1 meter, turning left by 90 degrees and turning right by 90 degrees. If the robot moves and hits the wall, then it will stay in its position and orientation. The robot's goal is to escape from this maze by reaching the end of the long corridor.
**Note: the answers in the following questions should not exceed 5 sentences.**

### Question 3.1 (4p)

Assume the robot receives a +1 reward signal for each time step taken in the
maze and +1000 for reaching the final goal (the end of the long corridor). Then you train the robot for a while, but it seems it still does not perform well at all for navigating to the end of the corridor in the maze. What is happening? Is there something wrong with the reward function?

---

The robot does not perform well because it can reach about or over 1000 during the train and then it never will escape from this maze. Moreover, if it gets +1 at each time steps, we will assign a positive reward all the time. As a consequence, it does not learn the way to escape at all. 

### Question 3.2 (4p)

If there is something wrong with the reward function, how could you fix it? If not, how to resolve the training issues?

---

We can fix this problem just assigning to it a bad rewards at each timestep (for instance -1) or we could also assign the value of zero if it has not escape yet. We can assign a positive reward (as +1) only if it has reached the exit. 

### Question 3.3 (2p)

The discounted return for a non-episodic task is defined as
$$
G_t = R_{t+1} + \gamma R_{t+2} + \gamma^2 R_{t+3} + \ldots
$$
where $\gamma \in [0, 1]$ is the discount factor.

Rewrite the above equation such that $G_t$ is alone on the left hand side and $G_{t+1}$ is on the right hand side.


---

\begin{equation}
G_t=R_{t+1}+\gamma(R_{t+2}+R_{t+3}+R_{t+4}+R_{t+5}+R_{t+6}+...)
=R_{t+1}+G_{t+1}
\end{equation}

### Question 3.4 (2p)

What is the sufficient condition for this infinite series to be a convergent series?

---

The sufficent condition for this infinite series to be convergent is that lambda must be less than 1.

### Question 3.5 (5p)

Suppose this infinite series is a convergent series, and each reward in the series is a constant of +1. We know the series is bounded, what is a simple formula for this bound ? Write it down without using summation.

---

**ANSWER HERE**


### Question 3.6 (5p)

Let the task be an episodic setting and the robot is running for $T = 5$ time steps. Suppose $\gamma = 0.9$, and the robot receives rewards along the way $R_1 = −1, R_2 = −0.5, R_3 = 2.5, R_4 = 1, R_5 = 3$. What are the values for $G_0, G_1, G_2, G_3, G_4, G_5$?

---
\begin{equation}{
G_5=0\\
G_4=R_5+\gamma G_5=R_5=3\\
G_3=R_4+\gamma G_4=1+0.9*3=3.7\\
G_2=R_3+\gamma G_3=2.5+0.9*3.7=5.83\\
G_1=R_2+\gamma G_2=-0.5+0.9*5.83=4.747\\
G_0=R_1+\gamma G_1=-1+0.9*4.747=3.27\\}
\end{equation}

### Question 3.7 (5p)

Suppose each reward in the series is increased by a constant $c$, i.e. $R_t \leftarrow R_t + c$.
Then how does it change $G_t$?

---


Since we know that (if the rewards are constant and equal to +1):

$$G_t=\sum_{k=0}^{\infty }{\gamma^k}=\frac{1}{1-\gamma}$$
if the rewards is c is constant and the rewards increase along the time, then the sum becomes :

$$G_t=\sum_{k=0}^{\infty }{c * \gamma^k}$$ since c is constant, it does not depend on k:
$$c* \sum_{k=0}^{\infty }{ \gamma^k}=\frac{c*1}{1-\gamma}=\frac{c}{1-\gamma}$$


### Question 3.8 (5p)

Now consider episodic tasks, and similar to Question 2.7, we add a constant $c$ to each reward, how does it change $G_t$?

---

Episodic tesks are definited as:
$$G_t=\sum_{k=0}^{T-t-1 }{\gamma^k R_k}$$
If the reward is increased by c at each time step:
$$G_t=\sum_{k=0}^{T-t-1 }{\gamma^k (R_k +c)}$$
 by splitting the sum:

$$G_t=\sum_{k=0}^{T-t-1 }{\gamma^k R_k } +\sum_{k=0}^{T-t-1 }{\gamma^k c}=$$
the first term is $G_t$ while the second is :
$$c\; \frac{1- \gamma^{T-t}}{1- \gamma}$$
---


## 4 Reinforcement Learning: Dynamic Programming (58p)

### Question 4.1 (5p)

Write down the Bellman optimality equation for the state value function without using expectation notation, but using probability distributions instead. 
Define all variables and probability distributions in bullet points.

---

**ANSWER HERE**

### Question 4.2 (5p)

Write down the Bellman optimality equation for the state-action value function without using expectation notation, but using probability distributions instead.
Define all variables and probability distributions in bullet points.

---

**ANSWER HERE**

### Question 4.3 (15p)

Consider a 4x4 gridworld depicted in the following table:

![Grid world](https://i.ibb.co/HdSdKJB/image.png)

The non-terminal states are $S = \{1, 2, \ldots, 14\}$ and the terminal states are $0, 15$.
There are four available actions for each state, that is $A = \{\text{up}, \text{down}, \text{left}, \text{right}\}$.
Assume the state transitions are deterministic and all transitions result in a negative reward of −1.
If the agent hits the boundary, then its state will remain unchanged, e.g. $p(s=8, r=−1|s=8, a=\text{left}) = 1$.
Note: In this exercise, we assume the policy is a deterministic
function and it initially maps each state to an arbitrary action.


Manually run the policy iteration algorithm for one outer iteration. Use the in-place policy iteration algorithm (directly using the updated values for the next value update).
To be specific, run the policy evaluation with a single pass through the states (16 equations, not until convergence) and one time policy improvement.
Assume the initial state value for all 16 cells is 0.0 and the policy initially always outputs the 'left' action.
Write down the equations and detailed numerical computations for the updated values of each cell.
Use a discount factor $\gamma = 0.5$.
Write down the policy after policy improvement.

Read more about this in Sutton & Barto's book http://www.incompleteideas.net/book/ebook/node43.html

---

**ANSWER HERE**

### Question 4.4 (12p)

Implement the environment as described in the code skeleton below.
Come up with your own solution and do not copy the code from a third party source.

Then test your implementation of GridWorld using the implementation of policy iteration provided below. Run the code multiple times. Do you always end up with the same policy? Why? (max 4 sentences)

---

I end up with the same policy becuase it is a deterministic approach. 


#### Imports

In [ ]:
import numpy as np
import itertools

np.set_printoptions(precision=3, linewidth=180)



#### Defining the problem

In [ ]:
class GridWorld:

    UP = 0
    DOWN = 1
    LEFT = 2
    RIGHT = 3
    table=np.arange(0, 16)
    table=table.reshape([4,4])
    #print("grid: \n\n", table)
    def __init__(self, side=4):
        self.side = side
        # -------------------------
        # Define integer states, actions, and final states as specified
        # in the problem description
    
        # TODO insert code here
        self.actions = np.array([self.DOWN, self.LEFT, self.RIGHT, self.UP])
        self.states = np.arange(0, 16)
        self.finals = np.array([0, 15])

        # -------------------------
        self.actions_repr = np.array(['↑', '↓', '←', '→'])

    def _is_terminal(self, s):
        # -------------------------
        # Return True if s is a terminal state and False otherwise
        return(s==15 or s==0)
        # TODO insert code here

        # -------------------------

    def _next_state(self, s, a):
        # -------------------------
        # Returns the next state of the environment if action a were taken
        # while in state s
        
        
        for i in self.table[0]:
            if(a==self.UP and s==i):
              return s
        
        for i in self.table[3]:
            if(a==self.DOWN and s==i):
              return s
        
        for i in self.table:
            j=i[0]
            if(a==self.LEFT and s==j):
              return s
        
        
        for i in self.table:
          j=i[3]
          if(a==self.RIGHT and s==j):
            return s
        
        for i in range(0,4):
            for j in range(0,4):
              if(a==self.UP and s==self.table[i][j]):
                return self.table[i-1][j]
              elif(a==self.DOWN and s==self.table[i][j]):
                return self.table[i+1][j]
              elif(a==self.LEFT and s==self.table[i][j]):
                return self.table[i][j-1]
              elif(a==self.RIGHT and s==self.table[i][j]):
                return self.table[i][j+1]
            
        # TODO insert code here

        # -------------------------

    def _reward(self, s, s_next, a):
        # -------------------------
        # Return the reward for the given transition as specified
        # in the problem description
        if(self._is_terminal(s)):
          return 0
        else:
          return -1
        # TODO insert code here

        # -------------------------
    
    def reset(self):
        # -------------------------
        # Set the internal state of the environment to be sampled uniformly
        # at random from the set of non-terminal states and return the state
        
        # TODO insert code here
        self.s = np.random.uniform(1,15)

        # -------------------------
    
    def step(self, a):
        old_s=self.s
        self.s=self._next_state(self.s,a)
        T=self._is_terminal(self.s)
        r=self._reward(old_s, self.s, a)
        return 


        # -------------------------
        # Advances the environment one step using action a and returns s, r, T
        # where s is the next state, r is the reward, and T is a boolean saying
        # whether the episode is done or not
        
        # TODO insert code here

        # -------------------------

    def print_policy(self, policy):
        P = np.array(policy).reshape(self.side, self.side)
        print(self.actions_repr[P])
  
    def print_values(self, values):
        V = np.array(values).reshape(self.side, self.side)
        print(V)

#### Policy iteration

In [ ]:
def transition_prob(s, s_next, a):
    return 1 if problem._next_state(s, a) == s_next else 0


def eval_policy(problem, policy, value, gamma=0.9, theta=0.01):
    p = transition_prob
    r = problem._reward

    while True:
        delta = 0
        for s in problem.states:
            v = value[s]
            value[s] = np.sum(
                [
                    p(s, next_s, policy[s])
                    * (r(s, next_s, policy[s]) + gamma * value[next_s])
                    for next_s in problem.states
                ]
            )
            delta = max(delta, abs(v - value[s]))

        if delta < theta:
            return value


def improve_policy(problem, policy, value, gamma=0.9):
    p = transition_prob
    r = problem._reward

    stable = True
    for s in problem.states:
        actions = problem.actions

        b = policy[s]
        policy[s] = actions[
            np.argmax(
                [
                    np.sum(
                        [
                            p(s, next_s, a) * (r(s, next_s, a) + gamma * value[next_s])
                            for next_s in problem.states
                        ]
                    )
                    for a in actions
                ]
            )
        ]
        if b != policy[s]:
            stable = False

    return stable


def policy_iteration(problem, gamma=0.9, theta=0.01):
    # Initialize a random policy
    policy = np.array([np.random.choice(problem.actions) for s in problem.states])
    print("Initial policy")
    problem.print_policy(policy)
    # Initialize values to zero
    values = np.zeros_like(problem.states, dtype=np.float32)

    # Run policy iteration
    stable = False
    for i in itertools.count():
        print(f"Iteration {i}")
        values = eval_policy(problem, policy, values, gamma, theta)
        problem.print_values(values)
        stable = improve_policy(problem, policy, values, gamma)
        problem.print_policy(policy)
        if stable:
            break

    return policy, values

In [ ]:
# Run the below code, please include the output in your submission
problem = GridWorld()
policy_iteration(problem, gamma=0.5)

Initial policy
[['↑' '↓' '→' '←']
 ['↑' '↑' '←' '↑']
 ['↓' '↓' '↑' '←']
 ['↑' '↑' '↓' '↑']]
Iteration 0
[[ 0.    -2.    -2.    -2.   ]
 [-1.    -2.    -2.    -2.   ]
 [-2.    -2.    -2.    -2.   ]
 [-2.    -2.    -1.992 -1.   ]]
[['←' '←' '←' '←']
 ['↑' '←' '↑' '↑']
 ['↑' '←' '↓' '↓']
 ['↑' '→' '→' '↓']]
Iteration 1
[[ 0.    -1.    -1.5   -1.75 ]
 [-1.    -1.5   -1.75  -1.875]
 [-1.5   -1.75  -1.508 -1.008]
 [-1.75  -1.508 -1.008 -0.008]]
[['←' '←' '←' '←']
 ['↑' '←' '←' '↓']
 ['↑' '←' '↓' '↓']
 ['↑' '→' '→' '↓']]
Iteration 2
[[ 0.    -1.    -1.5   -1.75 ]
 [-1.    -1.5   -1.75  -1.502]
 [-1.5   -1.75  -1.502 -1.002]
 [-1.75  -1.502 -1.002 -0.002]]
[['←' '←' '←' '←']
 ['↑' '←' '←' '↓']
 ['↑' '←' '↓' '↓']
 ['↑' '→' '→' '↓']]


(array([2, 2, 2, 2, 0, 2, 2, 1, 0, 2, 1, 1, 0, 3, 3, 1]),
 array([ 0.   , -1.   , -1.5  , -1.75 , -1.   , -1.5  , -1.75 , -1.502, -1.5  , -1.75 , -1.502, -1.002, -1.75 , -1.502, -1.002, -0.002], dtype=float32))

### Question 4.5 (5p)

Let's run policy iteration with $\gamma = 1$. Describe what is happening. Why is this the case? Give an example. What is $\gamma$ trading off and how does it affect policy iteration? (max 8 sentences)

---

With $\gamma$ equal to one it does not converge because we have an infinite sum of non-zero terms as this case. It shall be set less than 1.\\
We can have 2 cases: the first one when we set: $\gamma$ to zero and so the agent tries to maximize the immidiate reward (greedy/myopic), and the second case when we set $\gamma$ less than 1. Indeed, with $\gamma$ less than 1 we consider much more the future rewards. 

In [ ]:
policy_iteration(problem, gamma=1.0)

Initial policy
[['←' '↓' '←' '↓']
 ['→' '↑' '↑' '↑']
 ['→' '↑' '↑' '←']
 ['↓' '→' '→' '↑']]
Iteration 0


KeyboardInterrupt: ignored

### Question 4.6 (16p)

Implement Q-learning using the code skeleton below.
Come up with your own solution and do not copy the code from a third party source.
Then execute the block to show that your solution reached when $\gamma = 0.5$ is optimal.

In [ ]:
problem = GridWorld()
GAMMA = 0.5
sa_values = np.zeros((len(problem.states), len(problem.actions)), dtype=float)

def epsilon_greedy(a_values, epsilon):
    # -------------------------
    # This function takes a list a_values where each index i corresponds
    # to an estimate of the value of action i and then performs
    # epsilon-greedy action selection to sample and return an action
    
    # TODO insert code here
    pass
    # -------------------------

for i in range(100000):
    s = problem.reset()
    print(s)
    done = False
    while not done:
        # -------------------------
        # Perform one step of Q-learning here using sa_values to store
        # the action-value estimates and epsilon_greedy to perform the
        # action selection
        #
        # Play around to find a good step size

        # TODO insert code here
        pass
        # -------------------------


optimal_policy_state_values = policy_iteration(problem, gamma=GAMMA)[1]
learned_policy_state_values = np.max(sa_values, axis=1)

print('Optimal Policy State Values:')
print(optimal_policy_state_values)
print('Learned Policy State Values:')
print(learned_policy_state_values)
print('Root Mean Squared Value Error: {0:.8f}'.format(
    np.sqrt(np.mean(np.square(optimal_policy_state_values - learned_policy_state_values)))))

None
None


KeyboardInterrupt: ignored